version: 2.1

workflows:
  build:
    jobs:
      - build:
          context: java

jobs:
  build:
    working_directory: ~/work
    docker:
      - image: 570645264518.dkr.ecr.eu-central-1.amazonaws.com/build/circleci-openjdk-8:2020-11-18.15.180

    steps:
      - checkout

      - restore_cache:
          keys:
            - flexibee-{{ checksum "pom.xml" }}

      - run: mvn test

      - save_cache:
          paths:
            - ~/.m2
          key: flexibee-{{ checksum "pom.xml" }}

      - store_test_results:
          path: flexibee-core/target/surefire-reports
          destination: surefire-reports/

